name: procgen
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - tqdm
  - pytorch
  - torchvision
  - tensorboard
  - numpy
  - pip
  - pip:
    - gym==0.18.0
    - gym3==0.3.3
    - procgen==0.10.4